<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>be.vlaanderen.omgeving</groupId>
        <artifactId>vkbolodapi</artifactId>
        <version>0.1.4-SNAPSHOT</version>
    </parent>

    <artifactId>vkbolodapi-pkg</artifactId>
    <name>vkbo lod api - Packaging</name>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <app.username>vkbolodapi</app.username>
        <app.appname>vkbolodapi</app.appname>
        <app.installdir>/opt/vkbolodapi</app.installdir>
        <app.appconffile>${app.installdir}/${app.appname}.conf</app.appconffile>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>vkbolodapi-app</artifactId>
            <version>${project.version}</version>
            <type>jar</type>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <includeEmptyDirs>true</includeEmptyDirs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
                <executions>
                    <execution>
                        <id>copy-app</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifactItems>
                        <artifactItem>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>vkbolodapi-app</artifactId>
                            <version>${project.version}</version>
                            <type>jar</type>
                            <outputDirectory>
                                ${project.build.outputDirectory}/deb/root${app.installdir}
                            </outputDirectory>
                            <destFileName>vkbolodapi.jar</destFileName>
                            <overWrite>true</overWrite>
                        </artifactItem>
                    </artifactItems>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>1.14</version>
                <executions>
                    <execution>
                        <id>build-deb</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <controlDir>
                                ${project.build.outputDirectory}/deb/control
                            </controlDir>
                            <dataSet>
                                <data>
                                    <src>${project.build.outputDirectory}/deb/root</src>
                                    <type>directory</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/</prefix>
                                        <user>root</user>
                                        <group>root</group>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>deploy</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>bash</executable>
                    <workingDirectory>${project.build.directory}</workingDirectory>
                    <arguments>
                        <argument>-c</argument>
                       <argument>curl ${acd.repository.debian.login} --silent -XPUT "${acd.repository.debian.post.url}" -T ${project.artifactId}_*.deb</argument>
                    </arguments>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>